apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trioapp-qa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    codefresh.io/product: trio-app
    codefresh.io/app-group: trio
spec:
  destination:
    name: 'kc-v-qa'
    namespace: default
  source:
    path: manifests/trio-app/aperture-qa
    repoURL: 'https://github.com/danielm-codefresh/DevOps'
    targetRevision: main
    # plugin:
    #   name: kustomize-build-with-helm
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true
