apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: billing-usw
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: billing
spec:
  project: default
  source:
    path: manifests/simple-app-helm
    repoURL: https://github.com/danielm-codefresh/DevOps.git
    targetRevision: HEAD
  destination:
    name: target-usw
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      # - ServerSideApply=true
      - RespectIgnoreDifferences=false
