apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-asia
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/app-group: three-regions
    codefresh.io/product: multi-region-app
spec:
  project: default
  source:
    path: manifests/simple-app
    repoURL: https://github.com/danielm-codefresh/DevOps.git
    targetRevision: HEAD
  destination:
    name: kc-v-staging
    namespace: region-example
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      # - ServerSideApply=false
      - RespectIgnoreDifferences=false
